server:
  port: 8080
  
spring:
  cloud:
    gateway:
      routes:
        - id: seriesRoute #Identificando la ruta del service de producto
          uri: lb://serie-service #http://localhost:8082/ URL donde se hará el redirect segun el predicate definido
          predicates: #RReglas de análisis de una request
            - Path=/series/**
        
        - id: moviesRoute #Identificando la ruta del service de producto
          uri: http://localhost:8084/ #URL donde se hará el redirect segun el predicate definido
          predicates: #RReglas de análisis de una request
            - Path=/movies/**
            
        - id: catalogsRoute #Identificando la ruta del service de producto
          uri: http://localhost:8086/ #URL donde se hará el redirect segun el predicate definido
          predicates: #RReglas de análisis de una request
            - Path=/catalogs/**
       
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
