server:
  port: 8080
  
spring:
  cloud:
    gateway:
      routes:
        - id: seriesRoute #Identificando la ruta del service de producto
          uri: http://localhost:8082/ #URL donde se hará el redirect segun el predicate definido
          predicates: #RReglas de análisis de una request
            - Path=/series/**
       
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
