
server:
  port: 8086

spring:
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka

  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: catalogs
      port: 27017
      host: localhost  

resilience4j:
  circuitbreaker:
    instances:
      movies:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
        allowHealthIndicatorToFail: false

management:
  health:
    circuitbreakers:
      enabled: true
