server:
  port: 8082
  
spring:
  eureka:
    client:
      service-url:
        defaultZone: http://eureka:8761/eureka
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: series
      port: 27017
      host: mongodb    
        
    
