server:
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: password
    key-password: password
  port: 8082
  
spring:
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: amigoscode
      port: 27017
      host: localhost    
        
    
