version: "3.8"
services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

  catalog:
    image: catalog
    ports:
      - "8086:8086"
    restart: always
  
  movies:
    image: movies
    ports:
      - "8084:8084"
    restart: always

  series:
    image: series
    ports:
      - "8082:8082"
    restart: always

  configserver:
    image: configserver
    ports:
      - "8888:8888"
    restart: always
  
  eureka:
    image: eureka
    ports:
      - "8761:8761"
    restart: always

  mongodb:
    image: mongo
    container_name: "mongodb"
    command: mongod --auth
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
 
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb
 
  rabbitmq:
    image: rabbitmq:3.7.2-management
    ports:
      - "15672:15672"
      - "5672:5672"
   
volumes:
  data: {}
networks:
  default:
    name: mongodb_network
  